#!/bin/bash

# Check for the number of arguments passed
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Disable strict host key checking (not recommended for production)
ssh -o StrictHostKeyChecking=no -i "$ssh_key_path" $username@$server_ip "mkdir -p ~/"  # Create directory if it doesn't exist

# Transfer the file using scp with progress bar
scp -i "$ssh_key_path" "$file_path" $username@$server_ip:~/ &> /dev/null && echo "File transferred successfully!" || echo "Failed to transfer file."

exit 0
