#!/usr/bin/env bash

# Check for the number of arguments passed
if [ $# -lt 4 ]
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi


# Assign arguments to variables

file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Disable strict host key checking
scp -0 "StrictHostkeyChecking=no" -i "$file_path_ssh_key" "$path_to_file" "$username@$ip:~/"


#checking if transfer was successful
if [ $? -eq 0 ]
then
	echo "FILW WAS TRANSFERRED SUCCESSFUL"
else
	echo"FILE TRANSFER FAILED"
fi
