#!/usr/bin/env bash

# Corrected Script:
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

echo -e "\nSetting up Nginx.\n"

# Start nginx service
sudo service nginx start

# Allow nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Give ownership of website files to current user
sudo chown -R "$USER":"$USER" /var/www/html
# Change permissions of website files
sudo chmod -R 755 /var/www/html

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index with "Hello World!" content
echo -e "Hello World!" | sudo dd status=none of=/var/www/html/index.nginx-debian.html

# Restart nginx service
sudo service nginx restart

echo -e "\nCompleted.\n"

